### ISSUE TITLE
Implement Database

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#12]
- [x] Choose DB type
- [x] Spin up
- [x] Interface with web server/routing

**Comment by Inschato** [comment]
We need to determine exactly what our data we're manipulating, relations they have, and expected load. I think regardless we should just choose PostgreSQL because Jason Trill strongly suggested it and it's highly likely it will do everything we need it to. There are node libraries available for it too, of course.

**Comment by Inschato** [comment]
Spun up the empty DB and created some basic user partitioning.

Time to date: ~3 hours research, ~1 hour implenting

**Comment by hwkr** [comment]
@Inschato can you work on getting the server to talk to the database? Just pushing and pulling values at this point.

**Comment by Inschato** [comment]
New branch on https://github.com/Wubbadub/ClubHub/tree/feat/12/db

Implemented:
- API get request for site data (It currently doesn't check if the site's active flag is set or not)
- unused API calls for creating and updating sites

To do:
- [ ]  user related API calls (getting and saving user data)
- [ ]  update timestamps in appropriate places (when updating a site)
- [ ]  optionally add timestamps to admins relation (to track how long someone has been an admin for a particular site)
- [ ] directory related API (probably a separate feature/issue)
